accessing
testError
	^ self result exampleException